### ISSUE TITLE
CoffeeScript 2 Support

### ISSUE THREAD

**Issue by hotpancakes** [brunch/coffee-script-brunch#30]
Does coffee-script-brunch support CoffeeScript 2?

**Comment by shvaikalesh** [comment]
As soon as it reaches stable `2.0`.

**Comment by anildigital** [comment]
CoffeeScript 2.0 has released. Any update to support it. Thanks!

**Comment by pbgc** [comment]
Please update for Coffeescript 2

**Comment by marnen** [comment]
Stable 2 has been and gone. CoffeeScript is at 2.2.4 at this point.

**Comment by dsignr** [comment]
I think the author has abandoned this repository. Would be nice to atleast update the readme if this project isn't maintained anymore, instead of letting us all hanging in here, but, oh well. As a heavy coffeescript user, the lack of 2.0 support within brunch has forced me to explore Webpack where atleast things are stable. 

Anyway, I found someone else made a fork and added coffeescript 2.0 support here:
https://github.com/abalam666/coffeescript-brunch

**Comment by npoppeli** [comment]
I also looked at Webpack, but for the moment will stick with Brunch: too many config lines. And I've also tried Parcel: zero-config looks promising, but there's lots of stuff Parcel doesn't support yet.
I sent an email message to Paul Miller to ask if he or one of the other maintainers could look at this issue. The changes in the fork by abalam666 are tiny.

**Comment by pbgc** [comment]
I changed to webpack and will not look back! Webpack is a lot simpler than it looks!

**Comment by paulmillr** [comment]
done, webpack is still shit folks.

**Comment by dsignr** [comment]
WOW, that was totally unexpected. Thanks so much <3 I agree, Webpack is still shit. Zero configuration my a$$!
